/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { APIWallet__factory } from "./APIWallet__factory";
export { IERC20__factory } from "./IERC20__factory";
